# Generated by Django 4.2 on 2023-05-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson5', '0002_remove_user_name_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img/feedback_images')),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('feedback_type', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
